# Usar una imagen base de Python
FROM python:3.11.4-alpine3.17

# Establecer un directorio de trabajo
WORKDIR /app

# Copiar el archivo Python al contenedor
COPY . .

# Correr tu programa Python cuando se inicie el contenedor
CMD ["python", "./main.py"]
